version: "3"
services: 
    nginx:
        image: nginx:stable-alpine
        depends_on: 
            - node-app
    node-app:
        build: .
        environment: 
            - PORT=3000
        depends_on: 
            - mongo
            - redis

    mongo:
        image: mongo
        volumes: 
            - mongo-db:/data/db

    redis:
        image: redis


volumes: 
    mongo-db:


