version: "3"
services: 
    nginx:
        ports:
            - "3000:80"
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    node-app:
        build: 
            context: .
            args: 
                NODE_ENV: development
        volumes: 
            - ./:/app
            - /app/node_modules
        environment: 
            - NODE_ENV=development
            - MONGO_DB=myapp
            - MONGO_USER=admin
            - MONGO_PWD=password
            - SESSION_SECRET=secret
        command: npm run dev