name: Build & Push
on: [push]
jobs:
  build:
    name: Build Docker image and Push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            NODE=production
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/node-docker-tutorial:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/node-docker-tutorial:1.0.0
            gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-docker-tutorial:latest
            gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-docker-tutorial:1.0.0
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

